- name: '🏗️ ADR'
  color: 'f0b300'
  description: 'Architectural Decision Records'
- name: '🐞 Bugs'
  color: 'e99695'
  description: 'Bug reports'
- name: '🏯 Design'
  color: '742581'
  description: 'design / survey'
- name: '📝 Documentation'
  color: '0075ca'
  description: 'Documentation (include writing README.md)'
- name: '🏠 Chore'
  color: '0052cc'
  description: 'chore'
- name: '🚀 Feature'
  color: 'f19db5'
  description: 'new request and feature'
- name: '🔥 Priority:high'
  color: 'd93f0b'
  description: 'High Priority'
- name: '🏕️ Priority: low'
  color: '30e986'
  description: 'Low Priority Slowly Support'
- name: '❓Questions'
  color: 'fbca04'
  description: 'Questions'
- name: '🤖 renovate'
  color: '3e2b48'
  description: 'Renovate bot'
- name: '✅ Testing'
  color: '008672'
  description: 'Testing related'
