name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.vscode/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.vscode/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      # NOTE: setup jobがボトルネックになってきたら分割して改善する
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog with eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          fail_on_error: true
